name: Harbor
description: Harbor is a Spigot plugin that redefines how sleep works in your server, making it easier for all the online players to get in bed quickly and skip through the night!
main: xyz.nkomarn.harbor.Harbor
version: 1.6.3-SNAPSHOT
author: TechToolbox (@nkomarn)
website: https://nkomarn.xyz
softdepend: [Essentials]
api-version: 1.14

commands:
  harbor:
    description: "Base command for Harbor!"
    usage: "/harbor [subcommand]"

permissions:
  harbor.ignored:
    default: false
  harbor.admin:
    default: op